version: '3'
services:
  database:
    image: postgres:16.3-alpine3.20 # Nome da imagem
    container_name: postgresdatabase # Nome do container
    environment:
      - "POSTGRES_USER=postgres" # Nome do usuário do banco
      - "POSTGRES_PASSWORD=postgres" # Senha
      - "POSTGRES_DB=database_name" # Nome do banco de dados. Obs: Ainda não fiz funcionar.
    ports:
      - 55432:5432 # Porta na máquina física : Porta do container
    volumes:
      - pg-data:/var/lib/postgresql/data
      - pg-config:/etc/postgresql
    entrypoint: docker-entrypoint.sh -c 'config_file=/etc/postgresql/postgresql.conf'
volumes:
  pg-data:
  pg-config:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "$PWD/postgres_custom"
